"""App-wide constants.

Small on purpose. Anything that grows a policy belongs in the module that owns
that policy, not here.
"""

from __future__ import annotations

import os
from pathlib import Path

APP_NAME = 'hone'
APP_TITLE = 'HONE'
#: Joined with the glyph-set bullet at render time. Kept as parts rather than
#: one string because a literal '·' here would survive into the ASCII rung of
#: D20, which is a bug class this codebase has hit more than once.
#:
#: The three parts are D16's three views in order (Walkthrough, Practice,
#: Drill) and D8's three tiers read as a promise: what you have only read is
#: not what you can run, and what you can run is not what has been proved.
#: The previous tagline counted the modules, which made the front door a fact
#: that goes stale every time the roster moves, and a number is not a promise.
#: Must stay under 38 columns joined: `test.py` renders it at 40x16.
TAGLINE_PARTS = ('read it', 'run it', 'prove it')

#: D19a: the chord that always leaves a keystroke-capture screen. No drill may
#: claim it, which `validate.py` enforces. F10 was chosen because it is not a
#: plausible answer in any of the fifteen modules, it survives legacy decoding,
#: and it prints cleanly in the banner. Overridable with `--exit-key` for
#: anyone whose terminal or window manager swallows it.
#:
#: Known caveat, accepted: vanilla Emacs binds F10 to `menu-bar-open`. That is
#: not plausible drill content, so the collision is harmless.
EXIT_CHORD = 'F10'

#: Content is authored to fit here, and `test.py` asserts no screen overflows.
#: Id prefix for quiz items generated by inverting a drill (recognition
#: cards). Lives here rather than in loader.py because both the loader and the
#: state accounting need it, and state must not depend on the loader.
REVERSE_PREFIX = 'rev:'

MIN_COLS = 80
MIN_ROWS = 24


def data_dir() -> Path:
    """Where state lives, per D7. Honours XDG, falls back to the spec default."""
    base = os.environ.get('XDG_DATA_HOME') or (Path.home() / '.local' / 'share')
    return Path(base) / APP_NAME


def state_path() -> Path:
    return data_dir() / 'state.json'
